### ISSUE TITLE
Load yml with dynamic keys

### ISSUE THREAD

**Issue by phhoef** [Nikaple/nest-typed-config#123]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[X] Support request
</code></pre>

I am trying to load several quite complex yml files with `nest-typed-config`
For that reason, I am using the directoryLoader. The yml files are similiar to `docker-compose.yml` files.
There are section names, that are dynamic and not known to me. The user can specify these names.

The files are looking like this
```yml
test1:
  type: A
  endPoint: endpoint1.com
  port: 9000
  anyProp: 'abc'

test2:
  type: B
  endPoint: endpoint2.com
  port: 443
  path: /path/to/anything/
```

Depending on a `type` property, each section can have different properties.
But of course, same type means same properties.

My `RootConfig` looks like
```ts
export class AConfig{
    @Allow()
    type: 'A'

    @Allow()
    @IsUrl()
    endPoint: string

    @Allow()
    @IsNumber()
    port: number

    @Allow()
    @IsNotEmpty()
    anyProp: string
}

export class RootConfig {
    public readonly endpoints!: {
        [key: string]: AConfig | BConfig
    }
};
```

I see, that the yml files are loaded, but the validation fails.
Is there a easy way to achieve that?

I get this exception:
```
- config undefined does not match the following rules:
    - unknownValue: an unknown value was passed to the validate function, current config is `undefined`

at Function.validateWithClassValidator (/usr/src/app/node_modules/nest-typed-config/lib/typed-config.module.ts:135:13)
at Function.getDynamicModule (/usr/src/app/node_modules/nest-typed-config/lib/typed-config.module.ts:52:20)
at Function.forRoot (/usr/src/app/node_modules/nest-typed-config/lib/typed-config.module.ts:23:17)
```

**Comment by Nikaple** [comment]
The main concept of this module is that you can connect a Schema class with actual config. But under your situation, how would you want to consume your configurations? I mean, if I have two files, but both of them are `type: A`, which config the following code would inject?

```ts
class Service {
  constructor(private aConfig: AConfig) {}
}
```

Please further illustrate your use case, and I guess if you can define your config schema with [class-transformer](https://github.com/typestack/class-transformer), it will be easy to integrate with `nest-typed-config`.

**Comment by phhoef** [comment]
Thanks for your quick reply and pointing out the main concept of your module.
That's really helpful for me to understand - it's the very first time I am using `nest-typed-config`

I want to have different storage configurations.
For example, one is S3, another one filesystem, another one is FTP and so on.
All configs are for the same purpose, but they can differ depending on their type.

Would it be better to do it like this:
```yml
- name: 'test1'
  type: A
  endPoint: endpoint1.com
  port: 9000
  anyProp: 'abc'

- name: 'test2'
  type: B
  endPoint: endpoint2.com
  port: 443
  path: /path/to/anything/
  ```

Then it would be an array of these types. But again, each type can repeated as there might be several storages of type B. That is a problem, when I got you right, as the IoC container could not resolve the config
